import Foundation
import UDDF

// Example: Creating and writing a basic UDDF file

func createBasicUDDFFile() throws {
    // Create a generator section (required)
    let generator = Generator(
        name: "DiveLogPro",
        manufacturer: Manufacturer(
            id: "acme",
            name: "Acme Dive Software",
            contact: Contact(
                phone: "+1-555-DIVE-LOG",
                email: "support@divelogpro.example.com",
                homepage: "https://divelogpro.example.com"
            )
        ),
        version: "2.5.1",
        datetime: Date()
    )

    // Create the UDDF document
    let document = UDDFDocument(
        version: "3.2.1",
        generator: generator
    )

    // Write to file
    let outputURL = URL(fileURLWithPath: "dive_log.uddf")
    try UDDFSerialization.write(document, to: outputURL, prettyPrinted: true)

    print("UDDF file created successfully at: \(outputURL.path)")

    // Read it back
    let parsedDocument = try UDDFSerialization.parse(contentsOf: outputURL)
    print("Parsed generator: \(parsedDocument.generator.name)")
}

// Example: Parsing an existing UDDF file

func parseExistingUDDFFile(from url: URL) throws {
    do {
        // Parse the file
        let document = try UDDFSerialization.parse(contentsOf: url)

        // Access the data
        print("UDDF Version: \(document.version)")
        print("Generated by: \(document.generator.name)")

        if let version = document.generator.version {
            print("Generator version: \(version)")
        }

        if let manufacturer = document.generator.manufacturer {
            print("Manufacturer: \(manufacturer.name)")

            if let contact = manufacturer.contact {
                if let homepage = contact.homepage {
                    print("Homepage: \(homepage)")
                }
                if let email = contact.email {
                    print("Email: \(email)")
                }
            }
        }

        if let datetime = document.generator.datetime {
            print("Created: \(datetime)")
        }

    } catch UDDFError.fileNotFound(let url) {
        print("Error: File not found at \(url.path)")
    } catch UDDFError.invalidXML(let detail) {
        print("Error: Invalid XML - \(detail)")
    } catch UDDFError.missingGenerator {
        print("Error: UDDF file must contain a generator section")
    } catch {
        print("Unexpected error: \(error)")
    }
}

// Example: Round-trip conversion

func roundTripExample() throws {
    // Create original document
    let original = UDDFDocument(
        version: "3.2.1",
        generator: Generator(
            name: "TestApp",
            version: "1.0.0"
        )
    )

    // Write to XML
    let xmlData = try UDDFSerialization.write(original)

    // Parse back
    let parsed = try UDDFSerialization.parse(xmlData)

    // Verify they match
    assert(parsed.version == original.version)
    assert(parsed.generator.name == original.generator.name)
    assert(parsed.generator.version == original.generator.version)

    print("Round-trip successful!")

    // Print the generated XML
    if let xmlString = String(data: xmlData, encoding: .utf8) {
        print("\nGenerated XML:")
        print(xmlString)
    }
}

// Run examples
do {
    try createBasicUDDFFile()
    print("\n" + String(repeating: "-", count: 50) + "\n")
    try roundTripExample()
} catch {
    print("Error: \(error)")
}
